name: tf_env
channels:
  - conda-forge
  - apple
  - defaults

dependencies:
  - python=3.10  ## specify desired version
  - pip
  - tensorflow-deps
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - pip:
    - -r requirements.txt
